//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Athletics_Federation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Championship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Championship()
        {
            this.MainPanelOfJudges_Championships = new HashSet<MainPanelOfJudges_Championships>();
            this.PersonCompetitions = new HashSet<PersonCompetition>();
            this.ResultOfTeamPrimacies = new HashSet<ResultOfTeamPrimacy>();
        }
    
        public int ID { get; set; }
        public string NameChampionship { get; set; }
        public System.DateTime TheDateOfTheBeginning { get; set; }
        public System.DateTime TheDateOfTheEnding { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainPanelOfJudges_Championships> MainPanelOfJudges_Championships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonCompetition> PersonCompetitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultOfTeamPrimacy> ResultOfTeamPrimacies { get; set; }
    }
}
