//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Athletics_Federation
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainPanelOfJudges_Championships
    {
        public int ID { get; set; }
        public int IdChampionship { get; set; }
        public int IdMainPanelOfJudges { get; set; }
    
        public virtual Championship Championship { get; set; }
        public virtual MainPanelOfJudge MainPanelOfJudge { get; set; }
    }
}
