//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Athletics_Federation
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonCompetition
    {
        public int ID { get; set; }
        public int IdPatricipant { get; set; }
        public Nullable<int> Place { get; set; }
        public int IdGender { get; set; }
        public int IdCompetitions { get; set; }
        public int IdChampionship { get; set; }
        public string Result { get; set; }
        public Nullable<int> Points { get; set; }
    
        public virtual Championship Championship { get; set; }
        public virtual Competition Competition { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
