//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Athletics_Federation
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultOfTeamPrimacy
    {
        public int ID { get; set; }
        public int IdChempionship { get; set; }
        public Nullable<int> Place { get; set; }
        public Nullable<int> IdTeams { get; set; }
        public Nullable<int> Points { get; set; }
    
        public virtual Championship Championship { get; set; }
        public virtual Team Team { get; set; }
    }
}
